# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: messages.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto


@dataclass
class CustomerData(betterproto.Message):
    product: str = betterproto.string_field(1)
    note: str = betterproto.string_field(2)
    customer_name: str = betterproto.string_field(3)
    customer_number: str = betterproto.string_field(4)


@dataclass
class SellerData(betterproto.Message):
    product: str = betterproto.string_field(1)


@dataclass
class ListCustomerData(betterproto.Message):
    customers: List["CustomerData"] = betterproto.message_field(1)


@dataclass
class ServerError(betterproto.Message):
    error_message: str = betterproto.string_field(1)


@dataclass
class ServerSuccess(betterproto.Message):
    additional_information: str = betterproto.string_field(1)


@dataclass
class MessageToServer(betterproto.Message):
    customer_data: "CustomerData" = betterproto.message_field(
        1, group="StructMessageToServer"
    )
    seller_data: "SellerData" = betterproto.message_field(
        2, group="StructMessageToServer"
    )


@dataclass
class MessageToSeller(betterproto.Message):
    list_customer_data: "ListCustomerData" = betterproto.message_field(
        1, group="StructMessageToSeller"
    )
    server_error: "ServerError" = betterproto.message_field(
        2, group="StructMessageToSeller"
    )


@dataclass
class MessageToCustomer(betterproto.Message):
    server_error: "ServerError" = betterproto.message_field(
        1, group="StructMessageToCustomer"
    )
    success: "ServerSuccess" = betterproto.message_field(
        2, group="StructMessageToCustomer"
    )
